spring:
  datasource:
    url: jdbc:sqlserver://spring101.database.windows.net:1433;database=springboot1;user=admin@123@spring101;password=Rishi@2468;encrypt=true;trustServerCertificate=false;hostNamelnCertificate=*.database.windows.net;loginTimeout=30;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
